// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20170427 2017-04-27T12:07:38Z

#ifndef longBowReportTestAnything_About_h
#define longBowReportTestAnything_About_h
/**
 * Embedded string containing information for the what(1) command.
 *
 */
extern const char *longBowReportTestAnything_What;

/**
 * Return the name as a C string.
 *
 * @return The name as a C string.
 */
const char *longBowReportTestAnythingAbout_Name(void);

/**
 * Return the version as a C string.
 *
 * @return The version as a C string.
 */
const char *longBowReportTestAnythingAbout_Version(void);

/**
 * Return the About text as a C string.
 *
 * @return The About text as a C string.
 */
const char *longBowReportTestAnythingAbout_About(void);

/**
 * Return the minimum copyright notice as a C string.
 *
 * @return The minimum copyright notice as a C string.
 */
const char *longBowReportTestAnythingAbout_MiniNotice(void);

/**
 * Return the short copyright notice as a C string.
 *
 * @return The short copyright notice as a C string.
 */
const char *longBowReportTestAnythingAbout_ShortNotice(void);

/**
 * Return the long copyright notice as a C string.
 *
 * @return The long copyright notice as a C string.
 */
const char *longBowReportTestAnythingAbout_LongNotice(void);

#endif // longBowReportTestAnything_About_h
