// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20170427 2017-04-27T12:07:38Z

#include "longBowReportTestAnything_About.h"

const char *longBowReportTestAnything_What = "@(#)" "TestAnything " "0.1" " 2017-04-29T20:53:38.495620"
"@(#)" "\tCopyright (c) 2017 Palo Alto Research Center.";

const char *
longBowReportTestAnythingAbout_Name(void)
{
    return "TestAnything";
}

const char *
longBowReportTestAnythingAbout_Version(void)
{
    return "0.1";
}

const char *
longBowReportTestAnythingAbout_About(void)
{
    return "TestAnything ""0.1"" 2017-04-29T20:53:38.495620" "\nCopyright (c) 2017 Palo Alto Research Center.\n";
}

const char *
longBowReportTestAnythingAbout_MiniNotice(void)
{
    return "Copyright (c) 2017 Palo Alto Research Center.\n";
}

const char *
longBowReportTestAnythingAbout_ShortNotice(void)
{
    return "Copyright (c) 2017 Palo Alto Research Center.\n";
}

const char *
longBowReportTestAnythingAbout_LongNotice(void)
{
    return "Copyright (c) 2017 Palo Alto Resarch Center.\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at:\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.\n\n\n\n";
}

